### ISSUE TITLE
On user edition save it shows duplicate email error

### ISSUE THREAD

**Issue by ldaidone** [Erdiko/users#25]
<img width="1229" alt="cursor_and_erdiko_user_admin" src="https://cloud.githubusercontent.com/assets/1054693/25968854/3d52d774-3669-11e7-975e-4364d3f14955.png">

**Comment by saarmstrong** [comment]
We had an errant Email Dupe check on the postUpdate method which is pointless, since as update, of course this email exists. 

Removed and pushed commit to develop branch.
