### ISSUE TITLE
User events not logging

### ISSUE THREAD

**Issue by arroyo** [Erdiko/users#34]
Make sure key user events are being logged.

1. log user events listed below
2. Add units tests for every expected log

User events to log:
* login
* create user
* update user
* change password

**Comment by arroyo** [comment]
I moved the logout portion to a separate ticket #40

**Comment by arroyo** [comment]
@pinedamg  looks like the tests are still failing  https://circleci.com/gh/Erdiko/users/30

**Comment by pinedamg** [comment]
I've updated the repos from upstream and run the test and looks good. It could be possible that this build was made before of get the changes of the other repos?

![Selection_001.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/594ae34169b504001a0550bc/125516c66e82c728ace21e0d46db9196268197a080e78013f40cb2d86b56357c2301a03f32dfa17de74729580d5747ad410b5715f5f9892fa0b23477de0e08ffcd7f1d2598694ef1e1c84afd13b03289498fb7b88344c8eb3425e38e8f473d0c48.png)

**Comment by arroyo** [comment]
the errors are in UserModelTest.  I'll close this issue and create a new one
