### ISSUE TITLE
Update Password: Cannot read property password

### ISSUE THREAD

**Issue by pinedamg** [Erdiko/users#39]
Update Password: Cannot read property password

![selection_303](https://user-images.githubusercontent.com/818713/27550690-ecfa9904-5aa0-11e7-9a8c-7e390d626ea9.png)

**Comment by arroyo** [comment]
I believe this is a duplicate ticket.  @saarmstrong close this ticket out if it is working

**Comment by saarmstrong** [comment]
I cannot replicate this with the most up to date code. The latest versions of the code on GH& npm also have the #16 commit. 

@pinedamg please try to sync your repos and update the code locally.

**Comment by saarmstrong** [comment]
confirmed this is a duplicate after talking to @pinedamg
