### ISSUE TITLE
Create users documentation

### ISSUE THREAD

**Issue by arroyo** [Erdiko/users#41]
* Users (andy)
    * Overview
        * Intro
        * Setup / Configuration
    * Extending
    * Ajax Endpoints (we have old docs)
        * Endpoint 1
        * Endpoint 2, ...

**Comment by arroyo** [comment]
update readme too

**Comment by saarmstrong** [comment]
I created two PRs for the updated documentation:

- https://github.com/Erdiko/documentation/pull/1
- https://github.com/Erdiko/users/pull/48

**Comment by saarmstrong** [comment]
Overview
- Refactor DB section to reference scripts on user-admin

AJAX 
- remove redundant response stuff, only call out the stuff unique to each endpoint
- remove the `######` from the subsections, replace with bolds

Models (no real action yet)
- we should plan on moving this stuff to the dockblocks
- might need to hack phpdocs to output these docs
