### ISSUE TITLE
move authorizer security to the ajax methods

### ISSUE THREAD

**Issue by arroyo** [Erdiko/users#54]
Move authorizer security to the ajax methods 
 (from the models).  We should be checking the permissions in the controller. 
    
If the the user is not authorized then send back a message to the UI, “Sorry, you do not have permission”

*Add unit tests for the controllers
*Add tests for the case where they are authorized as well as the case where they are not authorized
        
Use curl to make the ajax call in the tests.  Since we are using Docker and running the tests within the container you can make a curl call to http://webserver

**Comment by ldaidone** [comment]
@arroyo "Move security from models to controllers"? As far as I can recall it would happens on version 2, using middleware. This will change the flow, and invalidate https://waffle.io/Erdiko/user-admin/cards/5939a3f088fb5a001a2a2c2b and all previous work done in users and could collide with other issues and open PRs

**Comment by arroyo** [comment]
Ha, was logged in as bot.

Overall building now will give us a head start on the middle ware.  Having a full erdiko v1 implementation may give us ideas on to best write the security for v2.
